#ifndef SOUND_SYSTEM_CONSTS_H
#define SOUND_SYSTEM_CONSTS_H

namespace sounds{

enum{
	PATH_SND_VOLUME,
	PATH_SND_WAVEFORM_LIST,
	PATH_SND_WAVEFORM_DIRECTORY,
	PATH_SND_CHANNEL_CONFIG,
	PATH_SND_MAX
};

}

#endif //SOUND_SYSTEM_CONSTS_H